#create database wytwornia_plytowa;
#use wytwornia_plytowa;
#drop table sprzedaz;
#drop table albumy;
#drop table zespoly;
#drop table opiekun;
create table opiekun (id_g int not null auto_increment, gatunek text not null, imie_o text, nazwisko text, ilosc_zespolow int not null, primary key (id_g));
create table zespoly (id_z int not null auto_increment, nazwa_z text not null, id_g int not null, ilosc_a int not null, primary key (id_z), foreign key (id_g) references opiekun(id_g));
create table albumy (id_a int not null auto_increment, nazwa_a text not null, id_z int not null, rok_wydania date, primary key (id_a), foreign key (id_z) references zespoly (id_z)); 
create table sprzedaz (id_s int not null auto_increment, sposob text, id_a int, ilosc int, primary key (id_s), foreign key (id_a) references albumy (id_a));
create trigger dodanie_zespolu after insert on zespoly for each row update opiekun set ilosc_zespolow = ilosc_zespolow + 1 where opiekun.id_g = new.id_g;
create trigger usuniecie_zespolu after delete on zespoly for each row update opiekun set ilosc_zespolow = ilosc_zespolow - 1 where opiekun.id_g = old.id_g;
create trigger dodanie_albumu after insert on albumy for each row update zespoly set ilosc_a = ilosc_a + 1 where zespoly.id_z = new.id_z;
create trigger usuniecie_albumu after delete on albumy for each row update zespoly set ilosc_a = ilosc_a - 1 where zespoly.id_z = old.id_z;
insert into opiekun values (null, 'jazz', 'Jan', 'Kowalski', 0);
insert into opiekun values (null, 'muzyka elektroniczna', 'Anna', 'Nowak', 0);
insert into opiekun values (null, 'rock', 'Adam', 'Kowalski', 0);
insert into opiekun values (null, 'pop', 'Wojciech', 'Zawadzki', 0);
insert into opiekun values (null, 'disco polo', 'Piotr', 'Wisniewski', 0);
insert into opiekun values (null, 'hip-hop', 'Zofia', 'Jastrzebska', 0);
insert into opiekun values (null, 'metal', 'Katarzyna', 'Misiak', 0);
insert into opiekun values (null, 'techno', 'Marta', 'Groszewska', 0);
insert into opiekun values (null, 'country', 'Maciej', 'Kujawa', 0);
insert into opiekun values (null, 'blues', 'Wojciech', 'Brzozowski', 0);
insert into opiekun values (null, 'reggae', 'Pawel', 'Krajewski', 0);
insert into opiekun values (null, 'muzyka instrumentalna', 'Anna', 'Osinska', 0);
insert into opiekun values (null, 'folk', 'Grzegorz', 'Gajewski', 0);
insert into opiekun values (null, 'new-wave', 'Agnieszka', 'Pietrzak', 0);
insert into opiekun values (null, 'muzyka alternatywna', 'Aleksandra', 'Osik', 0);
insert into opiekun values (null, 'trip-hop', 'Paulina', 'Grzybowska', 0); 
insert into opiekun values (null, 'muzyka niezalezna', 'Andrzej', 'Kruk', 0);
select * from opiekun;
insert into zespoly values (null, 'Emancipator', 2, 0);
insert into zespoly values (null, 'Twin Shadow', 14, 0);
insert into zespoly values (null, 'Archive', 15, 0);
insert into zespoly values (null, 'Flunk', 16, 0);
insert into zespoly values (null, 'Massive Attack', 16, 0);
insert into zespoly values (null, 'Royksopp', 2, 0);
insert into zespoly values (null, 'Regina Spector', 17, 0);
insert into zespoly values (null, 'Parov Stelar', 2, 0);
insert into zespoly values (null, 'Sonata Arctica', 7, 0);
insert into zespoly values (null, 'Kings of Leon', 3, 0);
insert into zespoly values (null, 'Evergrey', 7, 0);
insert into zespoly values (null, 'Yeasayes', 17, 0);
insert into zespoly values (null, 'Olafur Arnalds', 12, 0);
insert into zespoly values (null, 'Muse', 3, 0);
insert into zespoly values (null, 'In Flames', 7, 0);
insert into zespoly values (null, 'Lao Che', 3, 0);
insert into zespoly values (null, 'M83', 2, 0);
insert into zespoly values (null, 'Razorlight', 15, 0);
insert into zespoly values (null, 'Michael Jackson', 4, 0);
insert into zespoly values (null, 'Frnz Ferdinand', 17, 0);
insert into zespoly values (null, 'Arctic Monkeys', 17, 0);
insert into zespoly values (null, 'Stateless', 16, 0);
insert into zespoly values (null, 'The Streets', 6, 0);
insert into zespoly values (null, 'The Libertines', 15, 0);
insert into zespoly values (null, 'Th Black Keys', 10, 0);
insert into zespoly values (null, 'Datarock', 2, 0);
insert into zespoly values (null, 'Dry the River', 13, 0);
insert into zespoly values (null, 'I Blame Coco', 4, 0);
insert into zespoly values (null, 'Queens of the Stone Age', 3, 0);
insert into zespoly values (null, 'Firewind', 7, 0);
insert into zespoly values (null, 'Matisyahu', 11, 0);
insert into zespoly values (null, 'Chromeo', 2, 0);
insert into zespoly values (null, 'Zbigniew Preisner', 12, 0);
insert into zespoly values (null, 'Hurts', 14, 0);
insert into zespoly values (null, 'Tricky', 16, 0);
insert into zespoly values (null, 'Brodka', 4, 0);
insert into zespoly values (null, 'Michal Urbaniak', 1, 0);
insert into zespoly values (null, 'Leszek Mozdzer', 1, 0);
insert into zespoly values (null, 'Boys', 5, 0);
insert into zespoly values (null, 'Moderat', 8, 0);
select * from zespoly;
insert into albumy values (null, 'Far', 7, '2009-05-08');
insert into albumy values (null, 'Begin to Hope', 7, '2006-06-10');
insert into albumy values (null, 'Dusk to dawn', 1, '2013-01-29');
insert into albumy values (null, 'Mezzanine', 5, '1998-04-17');
insert into albumy values (null, 'Blue Lines', 5, '1991-04-08');
insert into albumy values (null, 'Heligoland', 5, '2010-02-05');
insert into albumy values (null, 'A Grand Dont Come for Free', 23, '2004-05-10');
insert into albumy values (null, 'Computers and Blues', 23, '2011-02-04');
insert into albumy values (null, 'Spark Seeker', 31, '2012-07-17');
insert into albumy values (null, 'Happiness - Deluxe Edition', 34, '2011-10-28');
insert into albumy values (null, 'Confess', 2, '2012-06-22');
insert into albumy values (null, 'Winterhearts Guild', 9, '2003-02-21');
insert into albumy values (null, 'You All Look the Same to Me', 3, '2002-09-16');
insert into albumy values (null, 'You Could Have It So Much Better', 20, '2005-09-28');
insert into albumy values (null, 'Come Clarity', 15, '2006-02-07');
insert into albumy values (null, 'Absolution', 14, '2003-09-21');
insert into albumy values (null, 'Melody A.M.', 6, '2001-10-08');
insert into albumy values (null, 'Coco', 8, '2009-09-14');
insert into albumy values (null, 'Found Songs', 13, '2009-04-19');
insert into albumy values (null, 'Junior', 6, '2009-03-18');
insert into albumy values (null, 'Recreation Day', 11, '2003-03-11');
insert into albumy values (null, 'Origin of Symmetry', 14, '2001-06-15');
insert into albumy values (null, 'Rough Cuts', 8, '2004-10-25');
insert into albumy values (null, 'The Inner Circle', 11, '2004-04-26');


